"""
Standalone script generator for compiling visual DAG workflows into clean, modular Python scripts.
"""

import re
import networkx as nx
from typing import Any, Dict, List

def sanitize_identifier(name: str) -> str:
    """Sanitizes variable or function name to valid Python identifier."""
    sanitized = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if sanitized and sanitized[0].isdigit():
        sanitized = "_" + sanitized
    return sanitized or "node"

def compile_dag_to_script(nodes: List[Dict[str, Any]], edges: List[Dict[str, Any]]) -> str:
    """
    Compiles DAG into a standalone, runnable Python script with modular functions
    and a pipeline coordinator.
    """
    # Build NetworkX graph
    g = nx.DiGraph()
    node_map = {n["id"]: n for n in nodes}

    for n in nodes:
        g.add_node(n["id"])

    for e in edges:
        if e["source"] in node_map and e["target"] in node_map:
            g.add_edge(e["source"], e["target"], sourceHandle=e.get("sourceHandle"), targetHandle=e.get("targetHandle"))

    if not nx.is_directed_acyclic_graph(g):
        raise ValueError("Cannot compile graph: Contains circular dependencies (cycles).")

    sorted_ids = list(nx.topological_sort(g))

    script_lines = [
        "#!/usr/bin/env python3",
        '"""',
        "Standalone Python Pipeline generated by DAG Python Execution Canvas.",
        "Auto-generated modular script.",
        '"""',
        "",
        "import sys",
        "import time",
        "import numpy as np",
        "import pandas as pd",
        "",
        "# ============================================================================",
        "# NODE FUNCTION DEFINITIONS",
        "# ============================================================================",
        ""
    ]

    # Map each node to its incoming variables mapping
    # targetHandle -> (sourceNodeId, sourceHandle)
    for node_id in sorted_ids:
        node_data = node_map[node_id]
        title = node_data.get("title", node_id)
        code = node_data.get("code", "").strip()
        inputs = node_data.get("inputs", [])
        outputs = node_data.get("outputs", [])

        func_name = f"node_{sanitize_identifier(node_id)}"
        args_str = ", ".join(inputs) if inputs else ""

        script_lines.append(f"# Node: {title} (ID: {node_id})")
        script_lines.append(f"def {func_name}({args_str}):")
        script_lines.append(f'    """')
        script_lines.append(f'    {title}')
        if inputs:
            script_lines.append(f'    Inputs: {", ".join(inputs)}')
        if outputs:
            script_lines.append(f'    Outputs: {", ".join(outputs)}')
        script_lines.append(f'    """')
        script_lines.append(f'    print(f"[{title}] Running...")')

        # Indent code body
        if code:
            for code_line in code.split("\n"):
                stripped = code_line.strip()
                if stripped.startswith("!"):
                    cmd = stripped[1:].strip()
                    indent = code_line[:len(code_line) - len(code_line.lstrip())]
                    script_lines.append(f"    {indent}import subprocess, sys")
                    script_lines.append(f"    {indent}_proc = subprocess.run({cmd!r}, shell=True, capture_output=True, text=True)")
                    script_lines.append(f"    {indent}sys.stdout.write(_proc.stdout)")
                    script_lines.append(f"    {indent}sys.stderr.write(_proc.stderr)")
                    script_lines.append(f"    {indent}if _proc.returncode != 0:")
                    script_lines.append(f"    {indent}    raise RuntimeError(f'Shell command failed with exit code {{_proc.returncode}}:\\n{{_proc.stderr.strip() or _proc.stdout.strip()}}')")
                else:
                    script_lines.append(f"    {code_line}")
        else:
            script_lines.append("    pass")

        # Return outputs
        if outputs:
            if len(outputs) == 1:
                script_lines.append(f"    return {outputs[0]}")
            else:
                script_lines.append(f"    return {', '.join(outputs)}")
        else:
            script_lines.append("    return None")

        script_lines.append("")
        script_lines.append("")

    # Pipeline coordinator function
    script_lines.extend([
        "# ============================================================================",
        "# PIPELINE EXECUTION HARNESS",
        "# ============================================================================",
        "",
        "def run_pipeline():",
        '    print("=" * 60)',
        '    print("Starting DAG Pipeline Execution")',
        '    print("=" * 60)',
        "    start_total = time.perf_counter()",
        "    context = {}",
        ""
    ])

    for node_id in sorted_ids:
        node_data = node_map[node_id]
        title = node_data.get("title", node_id)
        inputs = node_data.get("inputs", [])
        outputs = node_data.get("outputs", [])
        func_name = f"node_{sanitize_identifier(node_id)}"

        # Find where each input comes from
        # In edges: find edge where target == node_id
        arg_values = []
        for inp in inputs:
            # Check edge targeting this input handle
            found_src = None
            for e in edges:
                if e["target"] == node_id:
                    tgt_h = e.get("targetHandle")
                    if tgt_h == inp or not tgt_h or tgt_h in ["left", "top", "bottom", "right"]:
                        src_node_data = node_map.get(e["source"], {})
                        src_outs = src_node_data.get("outputs", [])
                        src_handle = e.get("sourceHandle")
                        if src_handle and src_handle not in ["left", "top", "bottom", "right"]:
                            out_var = src_handle
                        elif src_outs:
                            out_var = src_outs[0]
                        else:
                            out_var = inp
                        found_src = f"(context.get('{e['source']}_{out_var}') if '{e['source']}_{out_var}' in context else context.get('{out_var}'))"
                        break
            if not found_src:
                # Fallback to direct variable name in context
                found_src = f"context.get('{inp}')"
            arg_values.append(found_src)

        call_args = ", ".join(arg_values)

        script_lines.append(f"    # Execute {title}")
        script_lines.append(f"    t0 = time.perf_counter()")

        if outputs:
            if len(outputs) == 1:
                ret_var = f"out_{sanitize_identifier(node_id)}_{outputs[0]}"
                script_lines.append(f"    {ret_var} = {func_name}({call_args})")
                script_lines.append(f"    context['{node_id}_{outputs[0]}'] = {ret_var}")
                script_lines.append(f"    context['{outputs[0]}'] = {ret_var}")
            else:
                ret_vars = [f"out_{sanitize_identifier(node_id)}_{o}" for o in outputs]
                ret_vars_str = ", ".join(ret_vars)
                script_lines.append(f"    {ret_vars_str} = {func_name}({call_args})")
                for o, r_var in zip(outputs, ret_vars):
                    script_lines.append(f"    context['{node_id}_{o}'] = {r_var}")
                    script_lines.append(f"    context['{o}'] = {r_var}")
        else:
            script_lines.append(f"    {func_name}({call_args})")

        script_lines.append(f'    print(f"[{title}] Completed in {{(time.perf_counter() - t0)*1000:.2f}}ms\\n")')
        script_lines.append("")

    script_lines.extend([
        '    print("=" * 60)',
        '    print(f"Pipeline finished successfully in {{(time.perf_counter() - start_total)*1000:.2f}}ms")',
        '    print("=" * 60)',
        "    return context",
        "",
        "",
        'if __name__ == "__main__":',
        "    run_pipeline()",
        ""
    ])

    return "\n".join(script_lines)
